relaycorp/awala-jvm

- .github/workflows/ci.yml
- .gitignore
- .releaserc.yml
- build.gradle.kts
- gradle.properties
- package-lock.json
- package.json
> chore: Configure automatic releases to Maven repository

- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessage.kt
- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFSerializer.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessageTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFSerializerTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/StubRAMFMessage.kt
> feat: Make most RAMF fields optional

- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFSerializer.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFSerializerTest.kt
> feat(RAMF): Support serializations as InputStreams

- src/main/kotlin/tech/relaycorp/relaynet/CargoDeliveryRequest.kt
- src/test/kotlin/tech/relaycorp/relaynet/CargoDeliveryRequestTest.kt
Equivalent to the one in the JS implementation: https://github.com/relaycorp/relaynet-core-js/blob/8c4558fc67531eabb6e34debb5ccaba1bd690b36/src/lib/cargoRelay.ts#L8-L14
> feat: Implement cargo delivery request

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/Certificate.kt
- src/test/kotlin/tech/relaycorp/relaynet/CryptoUtils.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/cms/SignedDataTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/x509/CertificateTest.kt
> fix: Replace use of LocalDateTime with ZonedDateTime

- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessage.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessageTest.kt
> fix(RAMF): Implement method to tell if recipient address is private

- src/main/kotlin/tech/relaycorp/relaynet/pki.kt
- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessage.kt
- src/main/kotlin/tech/relaycorp/relaynet/ramf/RecipientAddressType.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/Certificate.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/CertificateException.kt
- src/test/kotlin/tech/relaycorp/relaynet/DummyCertPath.kt
- src/test/kotlin/tech/relaycorp/relaynet/PKITest.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessageTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/x509/CertificateTest.kt
Needed for https://github.com/relaycorp/relaynet-gateway-android/issues/16
See https://stackoverflow.com/questions/63020771/how-to-use-bouncycastle-to-get-the-certification-path-between-a-root-ca-and-an-e for background on the approach.
> feat: Implement certification path discovery and enforcement

- src/main/kotlin/tech/relaycorp/relaynet/messages/ParcelCollectionAck.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/control/ClientRegistration.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/control/ClientRegistrationAuthorization.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/control/ClientRegistrationRequest.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/control/NonceSignature.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/control/ParcelDelivery.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/payloads/CargoMessageSet.kt
- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFSerializer.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/asn1/ASN1Utils.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/ParcelCollectionAckTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/ClientRegistrationAuthorizationTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/ClientRegistrationRequestTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/ClientRegistrationTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/NonceSignatureTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/ParcelDeliveryTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/payloads/CargoMessageSetTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFSerializerTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/asn1/ASN1UtilsTest.kt
> fix(CargoMessageSet): Tag items implicitly

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/Certificate.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/x509/CertificateTest.kt
To fix this issue: https://issuetracker.google.com/issues/167784639
> fix: Use java.util.Date instead of java.sql.Date

- src/main/kotlin/tech/relaycorp/relaynet/messages/control/HandshakeChallenge.kt
- src/main/kotlin/tech/relaycorp/relaynet/messages/control/HandshakeResponse.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/HandshakeChallengeTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/HandshakeResponseTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/ParcelDeliveryTest.kt
Moving their ProtoBuf-based implementation from the PoWeb lib to here as an ASN1 sequence.
> feat: Implement handshake messages

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedData.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/cms/CMSUtils.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedDataTest.kt
Fixes relaycorp/relaynet-internet-gateway#204
See also: relaycorp/relayverse#16
> fix(CMS): Downgrade AES cipher mode from GCM to CBC

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/Certificate.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/x509/CertificateTest.kt
I'm doing this because I just got this exception from frankfurt.relaycorp.cloud, but I can't believe the server would return a malformed cert.
> feat(Certificate): Include cause to consider one malformed

- src/main/kotlin/tech/relaycorp/relaynet/CryptoAlgorithms.kt
- src/main/kotlin/tech/relaycorp/relaynet/pki.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/Keys.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/Certificate.kt
- src/test/kotlin/tech/relaycorp/relaynet/DateUtils.kt
- src/test/kotlin/tech/relaycorp/relaynet/PKITest.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessageTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/KeysTest.kt
> feat: Implement issuance and deserialisation of certificate for initial DH key

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedData.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/cms/RecipientIdentifier.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/payloads/EncryptedPayloadTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/cms/CMSUtils.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedDataTest.kt
Fixes #13
Note that:
- We won't be able to actually integrate this PR until https://github.com/relaycorp/relayverse/issues/27 has been fixed.
- The originator is not being exposed due to https://github.com/bcgit/bc-java/issues/894
> feat: Wrap handling of CMS EnvelopedData with channel session

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/Keys.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/KeysTest.kt
> feat: Implement key pair deserialisation

- src/main/kotlin/tech/relaycorp/relaynet/InvalidNodeConnectionParams.kt
- src/main/kotlin/tech/relaycorp/relaynet/PublicNodeConnectionParams.kt
- src/main/kotlin/tech/relaycorp/relaynet/SessionKey.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/DNS.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/asn1/ASN1Utils.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedData.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/cms/SessionKey.kt
- src/test/kotlin/tech/relaycorp/relaynet/PublicNodeConnectionParamsTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/SessionKeyTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/DNSTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/asn1/ASN1UtilsTest.kt
Needed for https://github.com/relaycorp/relayverse/issues/27
> feat: Implement PublicNodeConnectionParams

- src/main/kotlin/tech/relaycorp/relaynet/PublicNodeConnectionParams.kt
- src/main/kotlin/tech/relaycorp/relaynet/SessionKey.kt
- src/main/kotlin/tech/relaycorp/relaynet/keystores/PrivateKeyStore.kt
- src/main/kotlin/tech/relaycorp/relaynet/keystores/SessionPublicKeyData.kt
- src/main/kotlin/tech/relaycorp/relaynet/keystores/SessionPublicKeyStore.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedData.kt
- src/test/kotlin/tech/relaycorp/relaynet/PublicNodeConnectionParamsTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/SessionKeyTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/keystores/PrivateKeyStoreTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/keystores/SessionPublicKeyStoreTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/cms/EnvelopedDataTest.kt
> fix(SessionKey): Encode id as ByteArray instead of Integer

- .github/workflows/ci.yml
To mitigate gradle/wrapper-validation-action#40
> chore(CI): Validate Gradle wrapper once (on Linux)

- src/main/kotlin/tech/relaycorp/relaynet/wrappers/DNS.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/DNSTest.kt
To make domains like `ping.awala.services` work 🤦🏾‍♂
> fix(DNS): Support long TLDs

- src/main/kotlin/tech/relaycorp/relaynet/nodes/EndpointManager.kt
- src/main/kotlin/tech/relaycorp/relaynet/nodes/NodeManager.kt
- src/test/kotlin/tech/relaycorp/relaynet/nodes/EndpointManagerTest.kt
To be used in https://github.com/relaycorp/awala-endpoint-android/pull/163
> feat: Implement EndpointManager

- src/main/kotlin/tech/relaycorp/relaynet/ramf/EncryptedRAMFMessage.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/EncryptedRAMFMessageTest.kt
To help with https://github.com/relaycorp/awala-endpoint-android/pull/163
> feat(RAMF): Implement decryption straight from private key

- src/main/kotlin/tech/relaycorp/relaynet/messages/control/PrivateNodeRegistration.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/control/PrivateNodeRegistrationTest.kt
Needed for https://github.com/relaycorp/relayverse/issues/27
> feat(PrivateNodeRegistration): Add support for session keys

- src/main/kotlin/tech/relaycorp/relaynet/messages/CertificateRotation.kt
- src/test/kotlin/tech/relaycorp/relaynet/messages/CertificateRotationTest.kt
Per the spec. Found bug whilst testing compatibility with JS implementation.
> fix(CertificateRotation): Encode chain with explicit tagging

- src/main/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessage.kt
- src/main/kotlin/tech/relaycorp/relaynet/wrappers/x509/Certificate.kt
- src/test/kotlin/tech/relaycorp/relaynet/ramf/RAMFMessageTest.kt
- src/test/kotlin/tech/relaycorp/relaynet/wrappers/x509/CertificateTest.kt
Needed in https://github.com/relaycorp/relaynet-courier-android/pull/556
> feat(RAMFMessage): Implement `recipientCertificate` field

- src/main/kotlin/tech/relaycorp/relaynet/bindings/pdc/PDCClient.kt
See: https://github.com/relaycorp/awala-poweb-jvm/issues/302#issuecomment-1759569578
> fix(PDCClient): Fix `@Throws` declaration in `collectParcels()`
